---
name: Build and test

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          # Need to clone everything for the git tags.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install prereqs for setuptools
        run: pip install wheel

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          uv pip install --system -r requirements.txt

      # We have two cores so we can speed up the testing with xdist
      - name: Install pytest packages
        run: uv pip install --system pytest

      - name: Build and install
        run: uv pip install --system --no-deps -e .

      - name: Run tests
        run: |
          pytest
